### PR TITLE
adds circle magic to kickoff project

### PR DESCRIPTION
**Pull request by xh3b4sd**
I want to get https://github.com/giantswarm/cluster-operator/blob/master/pkg/v5/guestcluster into here so we can reuse it in different places.

### CODE REVIEW

**Review by MarcelMue — COMMENTED** [review]
That's some solid circle magic.

**Comment by xh3b4sd** [comment]
Wanna approve then mofo?

**Review by MarcelMue — APPROVED** [review]
Pressing the right buttons is hard.

**Comment by xh3b4sd** [comment]
Sweet.

**Pull request merged**
